### ISSUE TITLE
Error running the  demo notebook

### ISSUE THREAD

**Issue by Zacchaeus14** [DevashishPrasad/CascadeTabNet#60] opened 2020-07-31 11:15 UTC
Hi, when I ran the demo notebook on Colab, I got the following error:
<img width="869" alt="Screen Shot 2020-07-31 at 19 12 38" src="https://user-images.githubusercontent.com/64816317/89029977-18875700-d362-11ea-94b9-509d51f88cc7.png">
Should I upgrade mmdetection?

**Comment by AyanGadpal** [comment] 2020-08-07 03:59
Hey @Zacchaeus14 ,
No need to upgrade mmdetection
Just add  pip install mmcv==0.4.3, or use the lastest Demo notebook,
Duplicate of #56

**Closed** 2020-08-07 04:00 UTC
Labels: duplicate
